### ISSUE TITLE
Can't 'make env' (easy_install not found)

### ISSUE THREAD

**Issue by fiws** [chadwhitacre/mongs#15]
`make run` and `make env` do not work, because 'easy_install' does not exist.

``` shell
python2.7 ./vendor/virtualenv-1.6.4.py \
                --no-site-packages \
                --unzip-setuptools \
                --prompt="[mongs] " \
                --never-download \
                --extra-search-dir=./vendor/ \
                --distribute \
                ./env/
New python executable in ./env/bin/python2.7
Also creating executable in ./env/bin/python
Installing distribute.................................done.
Installing pip....
  Complete output from command /home/me/Document...gs/env/bin/python2.7 /home/me/Document...env/bin/easy_install ./vendor/pip-1.0.2.tar.gz:
  /home/me/Documents/test/mongs/env/bin/python2.7: can't open file '/home/me/Documents/test/mongs/env/bin/easy_install': [Errno 2] No such file or directory
----------------------------------------
...Installing pip...done.
Traceback (most recent call last):
  File "./vendor/virtualenv-1.6.4.py", line 1952, in <module>
    main()
  File "./vendor/virtualenv-1.6.4.py", line 810, in main
    never_download=options.never_download)
  File "./vendor/virtualenv-1.6.4.py", line 912, in create_environment
    install_pip(py_executable, search_dirs=search_dirs, never_download=never_download)
  File "./vendor/virtualenv-1.6.4.py", line 648, in install_pip
    filter_stdout=_filter_setup)
  File "./vendor/virtualenv-1.6.4.py", line 878, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/me/Document...gs/env/bin/python2.7 /home/me/Document...env/bin/easy_install ./vendor/pip-1.0.2.tar.gz failed with error code 2
make: *** [env] Error 1
```

OS: Ubuntu 13.04 64bit
Got Python 2.7.4 installed.

**Comment by jaraco** [comment]
Latest version runs on Python 3 and relies on venv and pip. Easy-install is not used.
